# Generated by Django 4.2.3 on 2023-07-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона')),
                ('country', models.SmallIntegerField(choices=[(1, 'Россия'), (2, 'Азербайджан'), (3, 'Армения'), (4, 'Белоруссия'), (5, 'Казахстан'), (6, 'Киргизия'), (7, 'Молдавия'), (8, 'Таджикистан'), (9, 'Узбекистан')], default=1, verbose_name='Страна')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
            },
        ),
    ]
