# Generated by Django 4.2.3 on 2023-07-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='country',
            field=models.CharField(choices=[('Россия', 'Россия'), ('Азербайджан', 'Азербайджан'), ('Армения', 'Армения'), ('Белоруссия', 'Белоруссия'), ('Казахстан', 'Казахстан'), ('Киргизия', 'Киргизия'), ('Молдавия', 'Молдавия'), ('Таджикистан', 'Таджикистан'), ('Узбекистан', 'Узбекистан')], default='Россия', verbose_name='Страна'),
        ),
    ]
