# Generated by Django 4.2.3 on 2023-07-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=50, null=True, verbose_name='slug')),
                ('view_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='Превью')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Разрешение на публикацию')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ('-published',),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-publish',), 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратные связи'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-published',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
