# Generated by Django 4.2.3 on 2023-08-01 19:26

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_blog_alter_category_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('В разработке', 'В разработке'), ('Выпуск в производстве', 'Выпуск в производстве')], default='В разработке', verbose_name='Название')),
                ('number', models.DecimalField(decimal_places=2, default=catalog.models.increment_version_number, max_digits=3, unique=True, verbose_name='Номер версии')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
                'ordering': ('-number',),
            },
        ),
    ]
