# Generated by Django 4.2.3 on 2023-08-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_user_product_user_product_blog_user_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='country',
            field=models.CharField(choices=[('Россия', 'Россия'), ('Азербайджан', 'Азербайджан'), ('Армения', 'Армения'), ('Белоруссия', 'Белоруссия'), ('Казахстан', 'Казахстан'), ('Киргизия', 'Киргизия'), ('Молдавия', 'Молдавия'), ('Таджикистан', 'Таджикистан'), ('Узбекистан', 'Узбекистан')], default='Россия', max_length=150, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='version',
            name='title',
            field=models.CharField(choices=[('В разработке', 'В разработке'), ('Выпуск в производстве', 'Выпуск в производстве')], default='В разработке', max_length=150, verbose_name='Название'),
        ),
    ]
