# Generated by Django 4.2.3 on 2023-08-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_identity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ключ'),
        ),
    ]
